name: Hello World CI

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Clone COSMoS repo into ecosystem
        run: |
          rm -rf cosmos
          git clone https://github.com/RahulAloth/COSMoS.git cosmos

      - name: Build
        run: ./scripts/build.sh

      - name: Test
        run: ./scripts/test.sh

      - name: Deploy
        run: ./scripts/deploy.sh

